### ISSUE TITLE
K8S ROS2 multicluster comunication / udp-multicast

### ISSUE THREAD

**Issue by ggari-robotnik** [fujitatomoya/ros_k8s#32]
I'm working on a project that aims to share ROS2 on multiple Kubernetes clusters.

The idea is that every robot is an independent Kubernetes cluster, and using [Liqo](https://github.com/LiqoTech/liqo) and other tools from the [Fluidos project](https://github.com/fluidos-project), we can offload ROS2 robotic loads to another robot.

I have a full simulation of Robotnik RB-Theron with Gazebo in ROS2, including all manifests, web RViz, and Gazebo implementations. Feel free to try. [robotnik-logistic-use-case](https://github.com/fluidos-project/robotic-logistics-use-case)

The problem I have is that I'm using Calico and Flannel as CNI, and if I deploy everything on the same Kubernetes node, everything works fine. But it doesn't work when there are multiple K8s nodes; I think it's a UDP multicast problem. I will have more problems with a multicluster offload.

As @fujitatomoya pointed out, WeaveNet is one of the few CNIs that allows UDP multicast, but the open-source branch is not maintained anymore.

I contacted the Zenoh team, and we tried to use the Zenoh router to use a centralized topology on that simulation. It works with simple publishers and nodes, but the /tf of the simulation and other topics do not work properly at the moment.

Has anyone tried any other options that do not imply multicast with Gazebo/Webots/real-robot?

**Comment by fujitatomoya** [comment]
@ggari-robotnik good news. Cilium supports multicast now, see the verified doc here https://github.com/fujitatomoya/ros_k8s/blob/master/docs/Setup_Kubernetes_Cluster.md#enable-multicast-wip
