### ISSUE TITLE
Request for Consideration of KubeEdge/Edgemesh

### ISSUE THREAD

**Issue by JoeyHwong-gk** [fujitatomoya/ros_k8s#9]
I am writing to express my interest in proposing [KubeEdge/Edgemesh](https://github.com/kubeedge/edgemesh) for your solution. 
Our team has been working on this project for some time now, and we believe it can provide significant value to #6  in terms of performance and functionality.

As a typical edge node, Robots in different areas are often not interconnected, and the inter-communication of traffic between applications is the primary requirement of the business. For this scenairo, EdgeMesh offers a solution.

>
- Enable users to have the ability to access robot-to-robot/robot-to-cloud/cloud-to-robot/robot-to-edge applications across different networks
- Compared to the mechanism of CoreDNS + Kube-Proxy + CNI service discovery, users only need to simply deploy an Agent to finish their goals

Thank you for taking the time to consider our proposal. I look forward to hearing back from you and the opportunity to further discuss this opportunity.

**Comment by fujitatomoya** [comment]
> As a typical edge node, Robots in different areas are often not interconnected, and the inter-communication of traffic between applications is the primary requirement of the business.

agree, it is likely that robots and edge devices are in the different network for some use cases.
on the other band, there also can be use cases like factories and logistics, in those cases all robots and edge devices are likely in the same network.

> Enable users to have the ability to access robot-to-robot/robot-to-cloud/cloud-to-robot/robot-to-edge applications across different networks

that will work just `out-of-the-box` so it is gonna be good solution for most users. something that we need to consider carefully here is,

- security, how we can protect and secure this network from attackers. using internet means zero trust security required.
- user defined configuration, and network namespace support. in particular use cases, user would want to separate the network logically in the network.
- performance, we can actually do this if we use VPN like technology, but the burden will be performance. every single time it secures and encodes the packets via server, that is really expensive for edge devices. maybe mesh network should be able to handle this network routing with kernel features like eBPF?

besides, I have mind that using KubeEdge with cloud web app running in cloud infra, and ros 2 app running with edgecore and and far edge devices run micro-ROS. i think that probably really good example architecture and use case for KubeEdge. I would come up with ideas.

thanks for sharing the information!

**Comment by JoeyHwong-gk** [comment]
actually, the opinions above are in line with our field of research.

as KubeEdge-based  design principles, `Edgemesh` is an extremely lightweight agent to run on resource constrained edge, which has performed excellently in some of our Ros/2 robots. We expect to push it to cover more scenarios and become a base communication component for robots. 

so，maybe we could take the liberty of inviting you for a discussion online in the near future, particulary with regards to `security` and `services discovery` or more.

as an expert in the field of k8s/ros, we believe you have a deep understanding and unique insight into this topic.

We have a community meeting on Tuesdays at 16:30-17:30 Beijing Time (biweekly, starting from Feb. 19th 2020). ([Convert to your timezone](https://www.thetimezoneconverter.com/?t=16%3A30&tz=GMT%2B8&)), and the next one should be February 14th. We are eagerly awaiting your participation and hope to continue your support in future cooperation.

**Comment by fujitatomoya** [comment]
> We have a community meeting on Tuesdays at 16:30-17:30 Beijing Time (biweekly, starting from Feb. 19th 2020). ([Convert to your timezone](https://www.thetimezoneconverter.com/?t=16%3A30&tz=GMT%2B8&)), and the next one should be February 14th. We are eagerly awaiting your participation and hope to continue your support in future cooperation.

I would love to, but time does not really work for me... it is 0:30 am, i could try but no promises. do you guys have mailing list or something?

**Comment by JoeyHwong-gk** [comment]
> I would love to, but time does not really work for me... it is 0:30 am, i could try but no promises. do you guys have mailing list or something?

Sorry for the time slot may not be convenient for you. We also have another SIG meeting on Tuesdays at 10:00-11:00 Beijing Time  ([Convert to your timezone](https://www.thetimezoneconverter.com/?t=10%3A00&tz=GMT%2B8&)), maybe this time will be more friendlier and I would like to invite you to attend the meeting if you are still interested. The discussion will still be centered around egdemesh as a communication component for robots and we welcome any comments and insights you have.

I would also like to inform you that the meeting will be held using the KubeEdge community meeting service, which means you can join us via [zoom.us/kubeedge](https://zoom.us/j/4167237304).

Thank you again for your attention and I look forward to the possibility of having you join us.

**Comment by fujitatomoya** [comment]
> Sorry for the schedule make you feel uncomfortable.

no no that is not what i mean. i am comfortable but time just does not really work for me.

> We also have another SIG meeting on Tuesdays at 10:00-11:00 Beijing Time ([Convert to your timezone](https://www.thetimezoneconverter.com/?t=10%3A00&tz=GMT%2B8&))

that could work, i have another meeting but i will be trying to join.

> I would also like to inform you that the meeting will be held using the KubeEdge community meeting service, which means you can join us via [zoom.us/kubeedge](https://zoom.us/j/4167237304).

i am happy to join, can you count me in?

is there anything i should do on my side?

**Comment by JoeyHwong-gk** [comment]
Woh, We are very much looking forward to having you join us and sharing your insights on the topic of `egdemesh` as a communication component for robotics.

As an expert of k8s and ros, we hope that if you'd like share some of your thoughts and comments during the meeting on the integration of ros and k8s in various scenarios. We would love to hear about your experiences and insights on cloud-native solutions and the potential benefits it could bring to `ros`.

In addition, as a ros expert, we hope that you can share some of the latest advancements and requirements in network and communication for ros during the meeting. Our team has limited knowledge in this area and we believe that your input will be invaluable.

Thank you for your time and consideration. We look forward to your participation in the meeting.

**Comment by fujitatomoya** [comment]
> In addition, as a ros expert, we hope that you can share some of the latest advancements and requirements in network and communication for ros during the meeting. Our team has limited knowledge in this area and we believe that your input will be invaluable.

of course, that is something I can do for sure as TSC and core system committer.

> we will send you a reminder email before the meeting starts to ensure you are well prepared.

appreciate it, looking forward to meeting you guys!

**Comment by fujitatomoya** [comment]
this discussion has been completed, and next step is to join KubeEdge SIG Robotics closing since there is no further task on this issue.
